// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/morning-night-guild/platform-app/pkg/ent/article"
	"github.com/morning-night-guild/platform-app/pkg/ent/articletag"
	"github.com/morning-night-guild/platform-app/pkg/ent/schema"
	"github.com/morning-night-guild/platform-app/pkg/ent/user"
	"github.com/morning-night-guild/platform-app/pkg/ent/userarticle"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescCreatedAt is the schema descriptor for created_at field.
	articleDescCreatedAt := articleFields[5].Descriptor()
	// article.DefaultCreatedAt holds the default value on creation for the created_at field.
	article.DefaultCreatedAt = articleDescCreatedAt.Default.(func() time.Time)
	// articleDescUpdatedAt is the schema descriptor for updated_at field.
	articleDescUpdatedAt := articleFields[6].Descriptor()
	// article.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	article.DefaultUpdatedAt = articleDescUpdatedAt.Default.(func() time.Time)
	// article.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	article.UpdateDefaultUpdatedAt = articleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// articleDescID is the schema descriptor for id field.
	articleDescID := articleFields[0].Descriptor()
	// article.DefaultID holds the default value on creation for the id field.
	article.DefaultID = articleDescID.Default.(func() uuid.UUID)
	articletagFields := schema.ArticleTag{}.Fields()
	_ = articletagFields
	// articletagDescID is the schema descriptor for id field.
	articletagDescID := articletagFields[0].Descriptor()
	// articletag.DefaultID holds the default value on creation for the id field.
	articletag.DefaultID = articletagDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	userarticleFields := schema.UserArticle{}.Fields()
	_ = userarticleFields
	// userarticleDescCreatedAt is the schema descriptor for created_at field.
	userarticleDescCreatedAt := userarticleFields[3].Descriptor()
	// userarticle.DefaultCreatedAt holds the default value on creation for the created_at field.
	userarticle.DefaultCreatedAt = userarticleDescCreatedAt.Default.(func() time.Time)
	// userarticleDescUpdatedAt is the schema descriptor for updated_at field.
	userarticleDescUpdatedAt := userarticleFields[4].Descriptor()
	// userarticle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userarticle.DefaultUpdatedAt = userarticleDescUpdatedAt.Default.(func() time.Time)
	// userarticle.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userarticle.UpdateDefaultUpdatedAt = userarticleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userarticleDescID is the schema descriptor for id field.
	userarticleDescID := userarticleFields[0].Descriptor()
	// userarticle.DefaultID holds the default value on creation for the id field.
	userarticle.DefaultID = userarticleDescID.Default.(func() uuid.UUID)
}
