// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/morning-night-guild/platform-app/pkg/ent/article"
	"github.com/morning-night-guild/platform-app/pkg/ent/predicate"
	"github.com/morning-night-guild/platform-app/pkg/ent/userarticle"
)

// UserArticleQuery is the builder for querying UserArticle entities.
type UserArticleQuery struct {
	config
	ctx         *QueryContext
	order       []userarticle.OrderOption
	inters      []Interceptor
	predicates  []predicate.UserArticle
	withArticle *ArticleQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserArticleQuery builder.
func (uaq *UserArticleQuery) Where(ps ...predicate.UserArticle) *UserArticleQuery {
	uaq.predicates = append(uaq.predicates, ps...)
	return uaq
}

// Limit the number of records to be returned by this query.
func (uaq *UserArticleQuery) Limit(limit int) *UserArticleQuery {
	uaq.ctx.Limit = &limit
	return uaq
}

// Offset to start from.
func (uaq *UserArticleQuery) Offset(offset int) *UserArticleQuery {
	uaq.ctx.Offset = &offset
	return uaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uaq *UserArticleQuery) Unique(unique bool) *UserArticleQuery {
	uaq.ctx.Unique = &unique
	return uaq
}

// Order specifies how the records should be ordered.
func (uaq *UserArticleQuery) Order(o ...userarticle.OrderOption) *UserArticleQuery {
	uaq.order = append(uaq.order, o...)
	return uaq
}

// QueryArticle chains the current query on the "article" edge.
func (uaq *UserArticleQuery) QueryArticle() *ArticleQuery {
	query := (&ArticleClient{config: uaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userarticle.Table, userarticle.FieldID, selector),
			sqlgraph.To(article.Table, article.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userarticle.ArticleTable, userarticle.ArticleColumn),
		)
		fromU = sqlgraph.SetNeighbors(uaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserArticle entity from the query.
// Returns a *NotFoundError when no UserArticle was found.
func (uaq *UserArticleQuery) First(ctx context.Context) (*UserArticle, error) {
	nodes, err := uaq.Limit(1).All(setContextOp(ctx, uaq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userarticle.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uaq *UserArticleQuery) FirstX(ctx context.Context) *UserArticle {
	node, err := uaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserArticle ID from the query.
// Returns a *NotFoundError when no UserArticle ID was found.
func (uaq *UserArticleQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = uaq.Limit(1).IDs(setContextOp(ctx, uaq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userarticle.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uaq *UserArticleQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := uaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserArticle entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserArticle entity is found.
// Returns a *NotFoundError when no UserArticle entities are found.
func (uaq *UserArticleQuery) Only(ctx context.Context) (*UserArticle, error) {
	nodes, err := uaq.Limit(2).All(setContextOp(ctx, uaq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userarticle.Label}
	default:
		return nil, &NotSingularError{userarticle.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uaq *UserArticleQuery) OnlyX(ctx context.Context) *UserArticle {
	node, err := uaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserArticle ID in the query.
// Returns a *NotSingularError when more than one UserArticle ID is found.
// Returns a *NotFoundError when no entities are found.
func (uaq *UserArticleQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = uaq.Limit(2).IDs(setContextOp(ctx, uaq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userarticle.Label}
	default:
		err = &NotSingularError{userarticle.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uaq *UserArticleQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := uaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserArticles.
func (uaq *UserArticleQuery) All(ctx context.Context) ([]*UserArticle, error) {
	ctx = setContextOp(ctx, uaq.ctx, "All")
	if err := uaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserArticle, *UserArticleQuery]()
	return withInterceptors[[]*UserArticle](ctx, uaq, qr, uaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uaq *UserArticleQuery) AllX(ctx context.Context) []*UserArticle {
	nodes, err := uaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserArticle IDs.
func (uaq *UserArticleQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if uaq.ctx.Unique == nil && uaq.path != nil {
		uaq.Unique(true)
	}
	ctx = setContextOp(ctx, uaq.ctx, "IDs")
	if err = uaq.Select(userarticle.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uaq *UserArticleQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := uaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uaq *UserArticleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uaq.ctx, "Count")
	if err := uaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uaq, querierCount[*UserArticleQuery](), uaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uaq *UserArticleQuery) CountX(ctx context.Context) int {
	count, err := uaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uaq *UserArticleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uaq.ctx, "Exist")
	switch _, err := uaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uaq *UserArticleQuery) ExistX(ctx context.Context) bool {
	exist, err := uaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserArticleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uaq *UserArticleQuery) Clone() *UserArticleQuery {
	if uaq == nil {
		return nil
	}
	return &UserArticleQuery{
		config:      uaq.config,
		ctx:         uaq.ctx.Clone(),
		order:       append([]userarticle.OrderOption{}, uaq.order...),
		inters:      append([]Interceptor{}, uaq.inters...),
		predicates:  append([]predicate.UserArticle{}, uaq.predicates...),
		withArticle: uaq.withArticle.Clone(),
		// clone intermediate query.
		sql:  uaq.sql.Clone(),
		path: uaq.path,
	}
}

// WithArticle tells the query-builder to eager-load the nodes that are connected to
// the "article" edge. The optional arguments are used to configure the query builder of the edge.
func (uaq *UserArticleQuery) WithArticle(opts ...func(*ArticleQuery)) *UserArticleQuery {
	query := (&ArticleClient{config: uaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	uaq.withArticle = query
	return uaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ArticleID uuid.UUID `json:"article_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserArticle.Query().
//		GroupBy(userarticle.FieldArticleID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uaq *UserArticleQuery) GroupBy(field string, fields ...string) *UserArticleGroupBy {
	uaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserArticleGroupBy{build: uaq}
	grbuild.flds = &uaq.ctx.Fields
	grbuild.label = userarticle.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ArticleID uuid.UUID `json:"article_id,omitempty"`
//	}
//
//	client.UserArticle.Query().
//		Select(userarticle.FieldArticleID).
//		Scan(ctx, &v)
func (uaq *UserArticleQuery) Select(fields ...string) *UserArticleSelect {
	uaq.ctx.Fields = append(uaq.ctx.Fields, fields...)
	sbuild := &UserArticleSelect{UserArticleQuery: uaq}
	sbuild.label = userarticle.Label
	sbuild.flds, sbuild.scan = &uaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserArticleSelect configured with the given aggregations.
func (uaq *UserArticleQuery) Aggregate(fns ...AggregateFunc) *UserArticleSelect {
	return uaq.Select().Aggregate(fns...)
}

func (uaq *UserArticleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uaq); err != nil {
				return err
			}
		}
	}
	for _, f := range uaq.ctx.Fields {
		if !userarticle.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uaq.path != nil {
		prev, err := uaq.path(ctx)
		if err != nil {
			return err
		}
		uaq.sql = prev
	}
	return nil
}

func (uaq *UserArticleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserArticle, error) {
	var (
		nodes       = []*UserArticle{}
		_spec       = uaq.querySpec()
		loadedTypes = [1]bool{
			uaq.withArticle != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserArticle).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserArticle{config: uaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(uaq.modifiers) > 0 {
		_spec.Modifiers = uaq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uaq.withArticle; query != nil {
		if err := uaq.loadArticle(ctx, query, nodes, nil,
			func(n *UserArticle, e *Article) { n.Edges.Article = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uaq *UserArticleQuery) loadArticle(ctx context.Context, query *ArticleQuery, nodes []*UserArticle, init func(*UserArticle), assign func(*UserArticle, *Article)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UserArticle)
	for i := range nodes {
		fk := nodes[i].ArticleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(article.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "article_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uaq *UserArticleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uaq.querySpec()
	if len(uaq.modifiers) > 0 {
		_spec.Modifiers = uaq.modifiers
	}
	_spec.Node.Columns = uaq.ctx.Fields
	if len(uaq.ctx.Fields) > 0 {
		_spec.Unique = uaq.ctx.Unique != nil && *uaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uaq.driver, _spec)
}

func (uaq *UserArticleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userarticle.Table, userarticle.Columns, sqlgraph.NewFieldSpec(userarticle.FieldID, field.TypeUUID))
	_spec.From = uaq.sql
	if unique := uaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uaq.path != nil {
		_spec.Unique = true
	}
	if fields := uaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userarticle.FieldID)
		for i := range fields {
			if fields[i] != userarticle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if uaq.withArticle != nil {
			_spec.Node.AddColumnOnce(userarticle.FieldArticleID)
		}
	}
	if ps := uaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uaq *UserArticleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uaq.driver.Dialect())
	t1 := builder.Table(userarticle.Table)
	columns := uaq.ctx.Fields
	if len(columns) == 0 {
		columns = userarticle.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uaq.sql != nil {
		selector = uaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uaq.ctx.Unique != nil && *uaq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range uaq.modifiers {
		m(selector)
	}
	for _, p := range uaq.predicates {
		p(selector)
	}
	for _, p := range uaq.order {
		p(selector)
	}
	if offset := uaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (uaq *UserArticleQuery) ForUpdate(opts ...sql.LockOption) *UserArticleQuery {
	if uaq.driver.Dialect() == dialect.Postgres {
		uaq.Unique(false)
	}
	uaq.modifiers = append(uaq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return uaq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (uaq *UserArticleQuery) ForShare(opts ...sql.LockOption) *UserArticleQuery {
	if uaq.driver.Dialect() == dialect.Postgres {
		uaq.Unique(false)
	}
	uaq.modifiers = append(uaq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return uaq
}

// UserArticleGroupBy is the group-by builder for UserArticle entities.
type UserArticleGroupBy struct {
	selector
	build *UserArticleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uagb *UserArticleGroupBy) Aggregate(fns ...AggregateFunc) *UserArticleGroupBy {
	uagb.fns = append(uagb.fns, fns...)
	return uagb
}

// Scan applies the selector query and scans the result into the given value.
func (uagb *UserArticleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uagb.build.ctx, "GroupBy")
	if err := uagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserArticleQuery, *UserArticleGroupBy](ctx, uagb.build, uagb, uagb.build.inters, v)
}

func (uagb *UserArticleGroupBy) sqlScan(ctx context.Context, root *UserArticleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uagb.fns))
	for _, fn := range uagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uagb.flds)+len(uagb.fns))
		for _, f := range *uagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserArticleSelect is the builder for selecting fields of UserArticle entities.
type UserArticleSelect struct {
	*UserArticleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uas *UserArticleSelect) Aggregate(fns ...AggregateFunc) *UserArticleSelect {
	uas.fns = append(uas.fns, fns...)
	return uas
}

// Scan applies the selector query and scans the result into the given value.
func (uas *UserArticleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uas.ctx, "Select")
	if err := uas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserArticleQuery, *UserArticleSelect](ctx, uas.UserArticleQuery, uas, uas.inters, v)
}

func (uas *UserArticleSelect) sqlScan(ctx context.Context, root *UserArticleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uas.fns))
	for _, fn := range uas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
