// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/morning-night-guild/platform-app/pkg/ent/article"
	"github.com/morning-night-guild/platform-app/pkg/ent/user"
	"github.com/morning-night-guild/platform-app/pkg/ent/userarticle"
)

// UserArticleCreate is the builder for creating a UserArticle entity.
type UserArticleCreate struct {
	config
	mutation *UserArticleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetArticleID sets the "article_id" field.
func (uac *UserArticleCreate) SetArticleID(u uuid.UUID) *UserArticleCreate {
	uac.mutation.SetArticleID(u)
	return uac
}

// SetUserID sets the "user_id" field.
func (uac *UserArticleCreate) SetUserID(u uuid.UUID) *UserArticleCreate {
	uac.mutation.SetUserID(u)
	return uac
}

// SetCreatedAt sets the "created_at" field.
func (uac *UserArticleCreate) SetCreatedAt(t time.Time) *UserArticleCreate {
	uac.mutation.SetCreatedAt(t)
	return uac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uac *UserArticleCreate) SetNillableCreatedAt(t *time.Time) *UserArticleCreate {
	if t != nil {
		uac.SetCreatedAt(*t)
	}
	return uac
}

// SetUpdatedAt sets the "updated_at" field.
func (uac *UserArticleCreate) SetUpdatedAt(t time.Time) *UserArticleCreate {
	uac.mutation.SetUpdatedAt(t)
	return uac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uac *UserArticleCreate) SetNillableUpdatedAt(t *time.Time) *UserArticleCreate {
	if t != nil {
		uac.SetUpdatedAt(*t)
	}
	return uac
}

// SetID sets the "id" field.
func (uac *UserArticleCreate) SetID(u uuid.UUID) *UserArticleCreate {
	uac.mutation.SetID(u)
	return uac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (uac *UserArticleCreate) SetNillableID(u *uuid.UUID) *UserArticleCreate {
	if u != nil {
		uac.SetID(*u)
	}
	return uac
}

// SetArticle sets the "article" edge to the Article entity.
func (uac *UserArticleCreate) SetArticle(a *Article) *UserArticleCreate {
	return uac.SetArticleID(a.ID)
}

// SetUser sets the "user" edge to the User entity.
func (uac *UserArticleCreate) SetUser(u *User) *UserArticleCreate {
	return uac.SetUserID(u.ID)
}

// Mutation returns the UserArticleMutation object of the builder.
func (uac *UserArticleCreate) Mutation() *UserArticleMutation {
	return uac.mutation
}

// Save creates the UserArticle in the database.
func (uac *UserArticleCreate) Save(ctx context.Context) (*UserArticle, error) {
	uac.defaults()
	return withHooks(ctx, uac.sqlSave, uac.mutation, uac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uac *UserArticleCreate) SaveX(ctx context.Context) *UserArticle {
	v, err := uac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uac *UserArticleCreate) Exec(ctx context.Context) error {
	_, err := uac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uac *UserArticleCreate) ExecX(ctx context.Context) {
	if err := uac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uac *UserArticleCreate) defaults() {
	if _, ok := uac.mutation.CreatedAt(); !ok {
		v := userarticle.DefaultCreatedAt()
		uac.mutation.SetCreatedAt(v)
	}
	if _, ok := uac.mutation.UpdatedAt(); !ok {
		v := userarticle.DefaultUpdatedAt()
		uac.mutation.SetUpdatedAt(v)
	}
	if _, ok := uac.mutation.ID(); !ok {
		v := userarticle.DefaultID()
		uac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uac *UserArticleCreate) check() error {
	if _, ok := uac.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article_id", err: errors.New(`ent: missing required field "UserArticle.article_id"`)}
	}
	if _, ok := uac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserArticle.user_id"`)}
	}
	if _, ok := uac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserArticle.created_at"`)}
	}
	if _, ok := uac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserArticle.updated_at"`)}
	}
	if _, ok := uac.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article", err: errors.New(`ent: missing required edge "UserArticle.article"`)}
	}
	if _, ok := uac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserArticle.user"`)}
	}
	return nil
}

func (uac *UserArticleCreate) sqlSave(ctx context.Context) (*UserArticle, error) {
	if err := uac.check(); err != nil {
		return nil, err
	}
	_node, _spec := uac.createSpec()
	if err := sqlgraph.CreateNode(ctx, uac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	uac.mutation.id = &_node.ID
	uac.mutation.done = true
	return _node, nil
}

func (uac *UserArticleCreate) createSpec() (*UserArticle, *sqlgraph.CreateSpec) {
	var (
		_node = &UserArticle{config: uac.config}
		_spec = sqlgraph.NewCreateSpec(userarticle.Table, sqlgraph.NewFieldSpec(userarticle.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = uac.conflict
	if id, ok := uac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := uac.mutation.CreatedAt(); ok {
		_spec.SetField(userarticle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uac.mutation.UpdatedAt(); ok {
		_spec.SetField(userarticle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := uac.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userarticle.ArticleTable,
			Columns: []string{userarticle.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ArticleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userarticle.UserTable,
			Columns: []string{userarticle.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserArticle.Create().
//		SetArticleID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserArticleUpsert) {
//			SetArticleID(v+v).
//		}).
//		Exec(ctx)
func (uac *UserArticleCreate) OnConflict(opts ...sql.ConflictOption) *UserArticleUpsertOne {
	uac.conflict = opts
	return &UserArticleUpsertOne{
		create: uac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserArticle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (uac *UserArticleCreate) OnConflictColumns(columns ...string) *UserArticleUpsertOne {
	uac.conflict = append(uac.conflict, sql.ConflictColumns(columns...))
	return &UserArticleUpsertOne{
		create: uac,
	}
}

type (
	// UserArticleUpsertOne is the builder for "upsert"-ing
	//  one UserArticle node.
	UserArticleUpsertOne struct {
		create *UserArticleCreate
	}

	// UserArticleUpsert is the "OnConflict" setter.
	UserArticleUpsert struct {
		*sql.UpdateSet
	}
)

// SetArticleID sets the "article_id" field.
func (u *UserArticleUpsert) SetArticleID(v uuid.UUID) *UserArticleUpsert {
	u.Set(userarticle.FieldArticleID, v)
	return u
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *UserArticleUpsert) UpdateArticleID() *UserArticleUpsert {
	u.SetExcluded(userarticle.FieldArticleID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserArticleUpsert) SetUserID(v uuid.UUID) *UserArticleUpsert {
	u.Set(userarticle.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserArticleUpsert) UpdateUserID() *UserArticleUpsert {
	u.SetExcluded(userarticle.FieldUserID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UserArticleUpsert) SetCreatedAt(v time.Time) *UserArticleUpsert {
	u.Set(userarticle.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserArticleUpsert) UpdateCreatedAt() *UserArticleUpsert {
	u.SetExcluded(userarticle.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserArticleUpsert) SetUpdatedAt(v time.Time) *UserArticleUpsert {
	u.Set(userarticle.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserArticleUpsert) UpdateUpdatedAt() *UserArticleUpsert {
	u.SetExcluded(userarticle.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserArticle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userarticle.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserArticleUpsertOne) UpdateNewValues() *UserArticleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(userarticle.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserArticle.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserArticleUpsertOne) Ignore() *UserArticleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserArticleUpsertOne) DoNothing() *UserArticleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserArticleCreate.OnConflict
// documentation for more info.
func (u *UserArticleUpsertOne) Update(set func(*UserArticleUpsert)) *UserArticleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserArticleUpsert{UpdateSet: update})
	}))
	return u
}

// SetArticleID sets the "article_id" field.
func (u *UserArticleUpsertOne) SetArticleID(v uuid.UUID) *UserArticleUpsertOne {
	return u.Update(func(s *UserArticleUpsert) {
		s.SetArticleID(v)
	})
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *UserArticleUpsertOne) UpdateArticleID() *UserArticleUpsertOne {
	return u.Update(func(s *UserArticleUpsert) {
		s.UpdateArticleID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserArticleUpsertOne) SetUserID(v uuid.UUID) *UserArticleUpsertOne {
	return u.Update(func(s *UserArticleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserArticleUpsertOne) UpdateUserID() *UserArticleUpsertOne {
	return u.Update(func(s *UserArticleUpsert) {
		s.UpdateUserID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserArticleUpsertOne) SetCreatedAt(v time.Time) *UserArticleUpsertOne {
	return u.Update(func(s *UserArticleUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserArticleUpsertOne) UpdateCreatedAt() *UserArticleUpsertOne {
	return u.Update(func(s *UserArticleUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserArticleUpsertOne) SetUpdatedAt(v time.Time) *UserArticleUpsertOne {
	return u.Update(func(s *UserArticleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserArticleUpsertOne) UpdateUpdatedAt() *UserArticleUpsertOne {
	return u.Update(func(s *UserArticleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserArticleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserArticleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserArticleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserArticleUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UserArticleUpsertOne.ID is not supported by MySQL driver. Use UserArticleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserArticleUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserArticleCreateBulk is the builder for creating many UserArticle entities in bulk.
type UserArticleCreateBulk struct {
	config
	builders []*UserArticleCreate
	conflict []sql.ConflictOption
}

// Save creates the UserArticle entities in the database.
func (uacb *UserArticleCreateBulk) Save(ctx context.Context) ([]*UserArticle, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uacb.builders))
	nodes := make([]*UserArticle, len(uacb.builders))
	mutators := make([]Mutator, len(uacb.builders))
	for i := range uacb.builders {
		func(i int, root context.Context) {
			builder := uacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserArticleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = uacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uacb *UserArticleCreateBulk) SaveX(ctx context.Context) []*UserArticle {
	v, err := uacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uacb *UserArticleCreateBulk) Exec(ctx context.Context) error {
	_, err := uacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uacb *UserArticleCreateBulk) ExecX(ctx context.Context) {
	if err := uacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserArticle.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserArticleUpsert) {
//			SetArticleID(v+v).
//		}).
//		Exec(ctx)
func (uacb *UserArticleCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserArticleUpsertBulk {
	uacb.conflict = opts
	return &UserArticleUpsertBulk{
		create: uacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserArticle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (uacb *UserArticleCreateBulk) OnConflictColumns(columns ...string) *UserArticleUpsertBulk {
	uacb.conflict = append(uacb.conflict, sql.ConflictColumns(columns...))
	return &UserArticleUpsertBulk{
		create: uacb,
	}
}

// UserArticleUpsertBulk is the builder for "upsert"-ing
// a bulk of UserArticle nodes.
type UserArticleUpsertBulk struct {
	create *UserArticleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserArticle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userarticle.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserArticleUpsertBulk) UpdateNewValues() *UserArticleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(userarticle.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserArticle.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserArticleUpsertBulk) Ignore() *UserArticleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserArticleUpsertBulk) DoNothing() *UserArticleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserArticleCreateBulk.OnConflict
// documentation for more info.
func (u *UserArticleUpsertBulk) Update(set func(*UserArticleUpsert)) *UserArticleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserArticleUpsert{UpdateSet: update})
	}))
	return u
}

// SetArticleID sets the "article_id" field.
func (u *UserArticleUpsertBulk) SetArticleID(v uuid.UUID) *UserArticleUpsertBulk {
	return u.Update(func(s *UserArticleUpsert) {
		s.SetArticleID(v)
	})
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *UserArticleUpsertBulk) UpdateArticleID() *UserArticleUpsertBulk {
	return u.Update(func(s *UserArticleUpsert) {
		s.UpdateArticleID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserArticleUpsertBulk) SetUserID(v uuid.UUID) *UserArticleUpsertBulk {
	return u.Update(func(s *UserArticleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserArticleUpsertBulk) UpdateUserID() *UserArticleUpsertBulk {
	return u.Update(func(s *UserArticleUpsert) {
		s.UpdateUserID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserArticleUpsertBulk) SetCreatedAt(v time.Time) *UserArticleUpsertBulk {
	return u.Update(func(s *UserArticleUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserArticleUpsertBulk) UpdateCreatedAt() *UserArticleUpsertBulk {
	return u.Update(func(s *UserArticleUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserArticleUpsertBulk) SetUpdatedAt(v time.Time) *UserArticleUpsertBulk {
	return u.Update(func(s *UserArticleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserArticleUpsertBulk) UpdateUpdatedAt() *UserArticleUpsertBulk {
	return u.Update(func(s *UserArticleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserArticleUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserArticleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserArticleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserArticleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
