services:
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:14.7-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  migrate:
    container_name: ${APP_NAME}-migrate
    build:
      context: .
      dockerfile: migrate/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - postgres
  core:
    container_name: ${APP_NAME}-core
    build:
      context: .
      dockerfile: core/Dockerfile
    ports:
      - ${APP_CORE_PORT}:8080
    environment:
      ENV: ${ENV}
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      NEWRELIC_APP_NAME: ${NEWRELIC_APP_NAME}
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - postgres
  api:
    container_name: ${APP_NAME}-api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - ${APP_API_PORT}:8080
    environment:
      ENV: ${ENV}
      API_KEY: ${API_KEY}
      APP_CORE_URL: http://core:8080
      NEWRELIC_APP_NAME: ${NEWRELIC_APP_NAME}
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}
      CORS_ALLOW_ORIGINS: http://localhost:5173
      CORS_DEBUG_ENABLE: true
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - core
