name: lint go
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/lint.go.yaml
      - "**/*.go"
      - .golangci.yaml
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./...
      # - name: Lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: v1.50.1
      #     args: --allow-parallel-runners
