name: lint proto
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/lint.proto.yaml
      - proto/**/*.proto
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.36.2
      - name: Install buf
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua install -t buf
      - name: Lint proto
        working-directory: ./proto
        run: buf lint
      - name: Format check proto
        working-directory: ./proto
        run: buf format -d --exit-code
