name: notice aqua pr
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  aqua:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Notice PR
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          urls=$(gh pr list --json url,title | jq -r '.[] | select( .title | contains("aquaproj") ) | .url ' )
          for url in ${urls}; do
            data="{\"text\":\"aquaの<${url}|PR>をマージするお時間です♪\"}"
            curl -X POST -H 'Content-type: application/json' --data ${data} ${{ secrets.SLACK_WEBHOOKS_URL_GITHUB }}
          done
